In [5]:
import pandas as pd
from pathlib import Path
import glob
import polars as pl
from deltalake import DeltaTable
import os

# Define the base data directory
base_data_dir = Path("../data")

# List of data stages to iterate through
data_stages = [
     "01_raw",
     "02_intermediate",
     "03_primary",
     "04_feature",
     "05_model_input",
     "06_models",
     "07_model_output",
     "08_reporting",
]

In [6]:
# Stage 01 raw
stage_01_raw = base_data_dir / data_stages[0]
df_01 = pd.read_csv(str(stage_01_raw / 'client_feedback.csv'))
df_01.head()

,Interaction_ID,Period,Tier,Portfolio_Name,Account_Name,Contact_Name,Contact_Title,Email,Language,Delivery_Owner,...,Contact_ID,Account_ID,NPS_Link,NPS_Score,NPS_Category,CSAT_Score,CSAT_Rating,Req_Understanding,Improvement_Comments,Other_Comments
0,2025-1_1,2025-1,Tail/Donate,The Bolts,America's Auto Auction,Khoa Ho,IT Systems and End User Support Manager,khoa.ho@americasaa.com,English,Jessica Estrella Menchaca Álvarez,...,003VM00000Pln5MYAR,0015d00003vZF4TAAW,https://www.surveymonkey.com/r/NPS-March-2025?...,9,Promoter,4,Satisfied,Agree,"Overall, I’ve had a positive experience with W...",NaN
1,2025-1_2,2025-1,Tail/Donate,The Bolts,America's Auto Auction,Olga Lazareva,Sr. Director of IT,olga.lazareva@americasaa.com,English,Jessica Estrella Menchaca Álvarez,...,0035d00007H1mGzAAJ,0015d00003vZF4TAAW,https://www.surveymonkey.com/r/NPS-March-2025?...,10,Promoter,5,Extremely satisfied,Strongly agree,Cannot think of anything that requires to be i...,NaN
2,2025-1_3,2025-1,Tail/Donate,The Bolts,AvalonBay Communities,Ramani Krishnamurthy,"Sr Director, Software Engineering",ramani_krishnamurthy@avalonbay.com,English,Jessica Estrella Menchaca Álvarez,...,0031K00003AsWe5QAF,0011K00002RKu0KQAT,https://www.surveymonkey.com/r/NPS-March-2025?...,10,Promoter,4,Satisfied,Neutral,-,NaN
3,2025-1_4,2025-1,Tail/Donate,The Bolts,AvalonBay Communities,Sang Huynh,"Manager, Software Engineering",sang_huynh@avalonbay.com,English,Jessica Estrella Menchaca Álvarez,...,0035d00007Cwn0EAAR,0011K00002RKu0KQAT,https://www.surveymonkey.com/r/NPS-March-2025?...,7,Passive,4,Satisfied,Agree,1. Empowering engineers with Investment in Cut...,NaN
4,2025-1_5,2025-1,Gold,The Nadals,Banco Azteca,Erika Lopez Peralta,Gerente Proyectos Y Producto Arquitectura De C...,erika.lopezp@elektra.com.mx,Spanish,Delia Norieta Ramirez Lopez,...,003VM00000Pi2jFYAR,0011K00002GnetTQAR,https://es.surveymonkey.com/r/NPS-March-2025-e...,10,Promoter,5,Extremely satisfied,Strongly agree,Un poco más de claridad en las vacaciones o au...,NaN

In [8]:
# Stage 01 raw Stats
df_01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Interaction_ID        144 non-null    object
 1   Period                144 non-null    object
 2   Tier                  143 non-null    object
 3   Portfolio_Name        144 non-null    object
 4   Account_Name          144 non-null    object
 5   Contact_Name          144 non-null    object
 6   Contact_Title         137 non-null    object
 7   Email                 144 non-null    object
 8   Language              104 non-null    object
 9   Delivery_Owner        126 non-null    object
 10  Opp_Owner             56 non-null     object
 11  Project_Manager       59 non-null     object
 12  Contact_ID            144 non-null    object
 13  Account_ID            144 non-null    object
 14  NPS_Link              144 non-null    object
 15  NPS_Score             144 non-null    int64
 16  NPS_Category          144 non-null    object
 17  CSAT_Score            144 non-null    int64
 18  CSAT_Rating           144 non-null    object
 19  Req_Understanding     144 non-null    object
 20  Improvement_Comments  136 non-null    object
 21  Other_Comments        42 non-null     object
dtypes: int64(2), object(20)
memory usage: 24.9+ KB

In [29]:
df_01['Account_Name'].unique().count()

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [ ]:
# Stage 02 primary
delta_table_path = base_data_dir / data_stages[1] / "clean_feedback.delta"

# This leverages the deltalake Rust-native library under the hood
df_02 = pl.read_delta(delta_table_path)
print(f"Shape: {df_delta_polars.shape}")
print("Polars DataFrame Head:")
print(df_02.head())
print("--- Statistics for Polars DataFrame Columns ---")
df_delta_polars.describe()

Shape: (144, 32)
Polars DataFrame Head:
--- Statistics for Polars DataFrame Columns ---

shape: (9, 33)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ Interactio ┆ Period ┆ Tier      ┆ … ┆ Rating    ┆ Responden ┆ detected_ ┆ language_ │
│ ---        ┆ n_ID       ┆ ---    ┆ ---       ┆   ┆ ---       ┆ t_Role    ┆ language  ┆ score     │
│ str        ┆ ---        ┆ str    ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│            ┆ str        ┆        ┆           ┆   ┆           ┆ str       ┆ str       ┆ f64       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 144        ┆ 144    ┆ 143       ┆ … ┆ 144       ┆ 144       ┆ 144       ┆ 144.0     │
│ null_count ┆ 0          ┆ 0      ┆ 1         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0.0       │
│ mean       ┆ null       ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0.9401    │
│ std        ┆ null       ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0.154568  │
│ min        ┆ 2025-1_1   ┆ 2025-1 ┆ Diamond   ┆ … ┆ Detractor ┆ User      ┆ en        ┆ 0.141382  │
│ 25%        ┆ null       ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0.981924  │
│ 50%        ┆ null       ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0.991769  │
│ 75%        ┆ null       ┆ null   ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0.99316   │
│ max        ┆ 2025-2_99  ┆ 2025-2 ┆ Tail/Dona ┆ … ┆ Promoter  ┆ User      ┆ pt        ┆ 0.994394  │
│            ┆            ┆        ┆ te        ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [26]:
unique_accounts_count = df_delta_polars['Account_Name'].n_unique()
print(f"Total unique values in 'Account_Name': {unique_accounts_count}")

Total unique values in 'Account_Name': 45

In [13]:
path = "../data/05_model_input/final_enriched_feedback.delta"
if os.path.exists(path):
    df_05 = pl.read_delta(path)
    print(df_05.head())
else:
    print('paila')

shape: (5, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ Interacti ┆ Interacti ┆ Customer_ ┆ NPS_Score ┆ … ┆ sentiment ┆ context_s ┆ Topic_ID ┆ Topic_Nam │
│ on_ID     ┆ on_Payloa ┆ ID        ┆ ---       ┆   ┆ _intensit ┆ core      ┆ ---      ┆ e         │
│ ---       ┆ d         ┆ ---       ┆ i64       ┆   ┆ y         ┆ ---       ┆ i64      ┆ ---       │
│ str       ┆ ---       ┆ str       ┆           ┆   ┆ ---       ┆ f64       ┆          ┆ str       │
│           ┆ str       ┆           ┆           ┆   ┆ f64       ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 2025-1_1  ┆ Overall,  ┆ 0015d0000 ┆ 9         ┆ … ┆ 0.4881    ┆ 0.2184    ┆ 1        ┆ 1.        │
│           ┆ I’ve had  ┆ 3vZF4TAAW ┆           ┆   ┆           ┆           ┆          ┆ Seamless  │
│           ┆ a         ┆           ┆           ┆   ┆           ┆           ┆          ┆ Collabora │
│           ┆ positive  ┆           ┆           ┆   ┆           ┆           ┆          ┆ tion      │
│           ┆ e…        ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2025-1_2  ┆ Cannot    ┆ 0015d0000 ┆ 10        ┆ … ┆ 0.1321    ┆ 0.0081    ┆ 3        ┆ 1.        │
│           ┆ think of  ┆ 3vZF4TAAW ┆           ┆   ┆           ┆           ┆          ┆ Candidate │
│           ┆ anything  ┆           ┆           ┆   ┆           ┆           ┆          ┆ Quality   │
│           ┆ that …    ┆           ┆           ┆   ┆           ┆           ┆          ┆ Improveme │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ …         │
│ 2025-1_3  ┆           ┆ 0011K0000 ┆ 10        ┆ … ┆ 0.5758    ┆ 0.0821    ┆ -1       ┆ null      │
│           ┆           ┆ 2RKu0KQAT ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2025-1_4  ┆ 1. Empowe ┆ 0011K0000 ┆ 7         ┆ … ┆ 0.8443    ┆ 0.7005    ┆ -1       ┆ null      │
│           ┆ ring      ┆ 2RKu0KQAT ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ engineers ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ with I…   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2025-1_5  ┆ A little  ┆ 0011K0000 ┆ 10        ┆ … ┆ 0.3997    ┆ -0.1418   ┆ -1       ┆ null      │
│           ┆ more      ┆ 2GnetTQAR ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ clarity   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ on vacat… ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [14]:
df_05

shape: (144, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ Interacti ┆ Interacti ┆ Customer_ ┆ NPS_Score ┆ … ┆ sentiment ┆ context_s ┆ Topic_ID ┆ Topic_Nam │
│ on_ID     ┆ on_Payloa ┆ ID        ┆ ---       ┆   ┆ _intensit ┆ core      ┆ ---      ┆ e         │
│ ---       ┆ d         ┆ ---       ┆ i64       ┆   ┆ y         ┆ ---       ┆ i64      ┆ ---       │
│ str       ┆ ---       ┆ str       ┆           ┆   ┆ ---       ┆ f64       ┆          ┆ str       │
│           ┆ str       ┆           ┆           ┆   ┆ f64       ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 2025-1_1  ┆ Overall,  ┆ 0015d0000 ┆ 9         ┆ … ┆ 0.4881    ┆ 0.2184    ┆ 1        ┆ 1.        │
│           ┆ I’ve had  ┆ 3vZF4TAAW ┆           ┆   ┆           ┆           ┆          ┆ Seamless  │
│           ┆ a         ┆           ┆           ┆   ┆           ┆           ┆          ┆ Collabora │
│           ┆ positive  ┆           ┆           ┆   ┆           ┆           ┆          ┆ tion      │
│           ┆ e…        ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2025-1_2  ┆ Cannot    ┆ 0015d0000 ┆ 10        ┆ … ┆ 0.1321    ┆ 0.0081    ┆ 3        ┆ 1.        │
│           ┆ think of  ┆ 3vZF4TAAW ┆           ┆   ┆           ┆           ┆          ┆ Candidate │
│           ┆ anything  ┆           ┆           ┆   ┆           ┆           ┆          ┆ Quality   │
│           ┆ that …    ┆           ┆           ┆   ┆           ┆           ┆          ┆ Improveme │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ …         │
│ 2025-1_3  ┆           ┆ 0011K0000 ┆ 10        ┆ … ┆ 0.5758    ┆ 0.0821    ┆ -1       ┆ null      │
│           ┆           ┆ 2RKu0KQAT ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2025-1_4  ┆ 1. Empowe ┆ 0011K0000 ┆ 7         ┆ … ┆ 0.8443    ┆ 0.7005    ┆ -1       ┆ null      │
│           ┆ ring      ┆ 2RKu0KQAT ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ engineers ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ with I…   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2025-1_5  ┆ A little  ┆ 0011K0000 ┆ 10        ┆ … ┆ 0.3997    ┆ -0.1418   ┆ -1       ┆ null      │
│           ┆ more      ┆ 2GnetTQAR ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ clarity   ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ on vacat… ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ 2025-2_14 ┆ Continue  ┆ 001G00000 ┆ 8         ┆ … ┆ 0.8029    ┆ 0.6305    ┆ -1       ┆ null      │
│ 0         ┆ to focus  ┆ 1r8fEyIAI ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ on automa ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ tio…      ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2025-2_14 ┆ The team  ┆ 001G00000 ┆ 7         ┆ … ┆ 0.9506    ┆ 0.8708    ┆ 2        ┆ 1.        │
│ 1         ┆ has been  ┆ 1r8fEyIAI ┆           ┆   ┆           ┆           ┆          ┆ Helpdesk  │
│           ┆ performin ┆           ┆           ┆   ┆           ┆           ┆          ┆ Team Exce │
│           ┆ g w…      ┆           ┆           ┆   ┆           ┆           ┆          ┆ llence    │
│ 2025-2_14 ┆ Nothing   ┆ 001G00000 ┆ 8         ┆ … ┆ 0.2098    ┆ 0.0379    ┆ -1       ┆ null      │
│ 2         ┆ off the   ┆ 1mx44zIAA ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ top of my ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ head…     ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2025-2_14 ┆ in        ┆ 001G00000 ┆ 10        ┆ … ┆ 0.2025    ┆ 0.0097    ┆ -1       ┆ null      │
│ 3         ┆           ┆ 1mx44zIAA ┆           ┆   ┆           ┆           ┆          ┆           │
│ 2025-2_14 ┆ More visi ┆ 001G00000 ┆ 7         ┆ … ┆ 0.1402    ┆ 0.017     ┆ -1       ┆ null      │
│ 4         ┆ bility of ┆ 1mx44zIAA ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ the wider ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│           ┆ o…        ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘